package AuctionApp;


/**
* AuctionApp/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Saturday, March 10, 2018 2:10:17 PM CST
*/

public interface AuctionOperations 
{
  String sayHello ();
} // interface AuctionOperations
